server:
  port: 8080
spring:
  application:
    name: com-boot-mongodb
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/test
